stages:
  - prebuild

# Check code standard for repository.
phpcs for complete project:
  image: registry.gitlab.com/mediamaisteri/devops/docker-images/moodlecs
  tags:
    - mm-moodle-unit-test
  stage: prebuild
  cache:
    key: "$CI_PIPELINE_ID"
    untracked: true
  allow_failure: false
  script:
    - phpcs --ignore=pix/*,*.js,login.php,*.xml .

create_badge_svg:
  stage: prebuild
  image: python:3.6.6
  tags:
    - docker
  script:
    - echo "Python other dependencies installation"
  after_script:
    - pip install anybadge
    - anybadge -l maisterilms -v "in the product" -f intheproduct.svg -c "blue"
  artifacts:
    paths:
        - intheproduct.svg
    when: always